## Makefile for Homework 3, 'The Game of Life', for CS410, 'Mastery in Programming'.

CC=gcc
DEBUG=-g
WARN=-Wall

game_of_life: game_of_life.c
	$(CC) $(WARN) $(DEBUG) -o game_of_life game_of_life.c

clean:
	rm game_of_life
	rm output.txt
 
